name: local_delivery_07
description: "07 Local Delivery - Hyperlocal Delivery Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Auth
  # Firebase Core & Auth
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.7.10

  # State Management
  provider: ^6.1.1

  # UI & Utilities
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  pinput: any              # OTP input fields
  intl: ^0.19.0            # Date formatting
  uuid: ^4.2.1             # Generate unique IDs

  # Maps & Location (Milestone 3)
  flutter_map: ^6.1.0       # OpenStreetMap widget
  latlong2: ^0.9.0           # Lat/Lng data type
  geolocator: ^11.0.0       # GPS location
  google_sign_in: ^6.2.1    # Google account login
  url_launcher: ^6.2.5      # Open phone dialer, URLs
  image_picker: ^1.0.7      # Pick photo from camera/gallery
  flutter_local_notifications: ^17.0.0  # Local push notifications

  # Charts (Admin Dashboard)
  fl_chart: ^0.65.0          # Analytics charts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
