// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWROXyqAKFMVePNYrJtenB9sQIUrxmpM',
    appId: '1:330945316904:web:64f24a7792a2c1ceca8d1d',
    messagingSenderId: '330945316904',
    projectId: 'local-delivery-cse489',
    authDomain: 'local-delivery-cse489.firebaseapp.com',
    storageBucket: 'local-delivery-cse489.firebasestorage.app',
    measurementId: 'G-HVPETGP4D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1BP4NoGUlIDw8smah0XxbSYf4U77Eqb4',
    appId: '1:330945316904:android:d942128c8b237193ca8d1d',
    messagingSenderId: '330945316904',
    projectId: 'local-delivery-cse489',
    storageBucket: 'local-delivery-cse489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3xzVxfu3bAWkOaKdl3tq3Q0SOEMKTCPc',
    appId: '1:330945316904:ios:e6625f9430a9807dca8d1d',
    messagingSenderId: '330945316904',
    projectId: 'local-delivery-cse489',
    storageBucket: 'local-delivery-cse489.firebasestorage.app',
    iosBundleId: 'com.example.localDelivery07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3xzVxfu3bAWkOaKdl3tq3Q0SOEMKTCPc',
    appId: '1:330945316904:ios:e6625f9430a9807dca8d1d',
    messagingSenderId: '330945316904',
    projectId: 'local-delivery-cse489',
    storageBucket: 'local-delivery-cse489.firebasestorage.app',
    iosBundleId: 'com.example.localDelivery07',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAWROXyqAKFMVePNYrJtenB9sQIUrxmpM',
    appId: '1:330945316904:web:402f2958b6c16aebca8d1d',
    messagingSenderId: '330945316904',
    projectId: 'local-delivery-cse489',
    authDomain: 'local-delivery-cse489.firebaseapp.com',
    storageBucket: 'local-delivery-cse489.firebasestorage.app',
    measurementId: 'G-4J1CK3LGSG',
  );
}
